inherit_from:
  - https://raw.githubusercontent.com/cookpad/guides/master/.rubocop.yml

AllCops:
  TargetRubyVersion: 2.5

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
